language: cpp
sudo: false
os:
 - linux
branches:
  only:
    - master
notifications:
  email:
#    recipients:
#      - nialldouglas14@gmail.com

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
#    - llvm-toolchain-precise-3.8  ## not currently working due to bad source signing key
    packages:
    - g++-6

before_install:
 - git submodule update --init --recursive

script:
 - RESULT=0
 - cd test
# - ./withgcc.sh
 - g++-6 -std=c++14 -Wall -Wextra -o atuple -O3 atuple.cpp || RESULT=1
 - ./atuple || RESULT=1
 - g++-6 -std=c++14 -Wall -Wextra -o ringbuffer_log -O3 ringbuffer_log.cpp || RESULT=1
 - ./ringbuffer_log || RESULT=1
 - g++-6 -std=c++14 -fopenmp -Wall -Wextra -o spinlock_tribool -O3 spinlock_tribool.cpp || RESULT=1
 - ./spinlock_tribool || RESULT=1
 - exit $RESULT
 
after_success:
# - bash -x ./update_coveralls.sh `pwd`

after_failure:
